name: Frontend CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Копирование проекта в рабочую директорию
        run: |
          mkdir -p /home/okr_web
          ls
          ls ./okr_web
          cp -r ./okr_web /home/okr_web

      - name: Перезапуск Nginx
        run: sudo systemctl restart nginx
      



      